name: Build

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macOS-10.15 ]
        python: [ 37 ]
        bitness: [ 64 ]
        manylinux_image: [ manylinux1, manylinux2010 ]
        include:
          # Run 32 and 64 bit version in parallel for Linux and Windows
          - os: windows-latest
            bitness: 64
            python: 37
            platform_id: win_amd64
          - os: ubuntu-latest
            bitness: 64
            python: 37
            platform_id: manylinux_x86_64
          - os: macos-latest
            bitness: 64
            python: 37
            platform_id: macosx_x86_64
        exclude:
          - os: macos-latest
            bitness: 32
          # Remove manylinux1 from the windows and osx build matrix since
          # manylinux_image is not used for these platforms
          - os: windows-latest
            manylinux_image: manylinux1
          - os: macos-latest
            manylinux_image: manylinux1

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        working-directory: ./python

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        working-directory: ./python
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl